name: Python Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest mypy pylint
    
    - name: Run pylint
      run: |
        pylint *.py --disable=all --enable=E --ignore-patterns=test_* || true
    
    - name: Run mypy
      run: |
        mypy . --ignore-missing-imports || true
    
    - name: Run pytest
      run: |
        python -m pytest tests/ -v || true
