name: Python Checks

on:
  push:
    branches: ["main", "prod"]
  pull_request:
    branches: ["main", "prod"]
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}  # make 'import app' work

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest mypy pylint

      - name: Run pytest
        run: python -m pytest -q

      # keep type/lint non-blocking so CI stays green
      - name: Run mypy (soft)
        run: mypy app.py || true

      - name: Run pylint (soft; app only)
        run: pylint app.py || true
